USE [master]
GO
/****** Object:  Database [webMall]    Script Date: 2/7/2018 2:48:53 AM ******/
CREATE DATABASE [webMall]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'webMall', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\webMall.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'webMall_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\webMall_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [webMall] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [webMall].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [webMall] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [webMall] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [webMall] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [webMall] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [webMall] SET ARITHABORT OFF 
GO
ALTER DATABASE [webMall] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [webMall] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [webMall] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [webMall] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [webMall] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [webMall] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [webMall] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [webMall] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [webMall] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [webMall] SET  DISABLE_BROKER 
GO
ALTER DATABASE [webMall] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [webMall] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [webMall] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [webMall] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [webMall] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [webMall] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [webMall] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [webMall] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [webMall] SET  MULTI_USER 
GO
ALTER DATABASE [webMall] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [webMall] SET DB_CHAINING OFF 
GO
ALTER DATABASE [webMall] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [webMall] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [webMall] SET DELAYED_DURABILITY = DISABLED 
GO
USE [webMall]
GO
/****** Object:  User [Shop_Owner]    Script Date: 2/7/2018 2:48:53 AM ******/
CREATE USER [Shop_Owner] FOR LOGIN [Shop_Owner] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_owner] ADD MEMBER [Shop_Owner]
GO
/****** Object:  Table [dbo].[category]    Script Date: 2/7/2018 2:48:53 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[category](
	[id] [int] NOT NULL,
	[name] [varchar](50) NULL,
	[description] [varchar](255) NULL,
	[image_url] [varchar](50) NULL,
	[is_active] [bit] NULL,
 CONSTRAINT [PK_category] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
USE [master]
GO
ALTER DATABASE [webMall] SET  READ_WRITE 
GO
